service: PHReviewIntegrationHandler

frameworkVersion: '>=3.19.0'
plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - "@agiledigital/serverless-sns-sqs-lambda"

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: ap-southeast-2
  logRetentionInDays: 60 # how long logs are kept in CloudWatch
  environment:
    # required Environment Variables. Don't remove.
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    service: ${self:service}
  tags:
    Application: ${self:service}
    Stage: ${self:provider.stage}

configValidationMode: warn

package:
  patterns:
    - src/** # include
    #exclude
    - '!*'

functions:
  PHReviewIntegrationHandler:
    handler: src/handler.handler
    description: The product hunt review integration handler
    memorySize: 128
    timeout: 800
    iamRoleStatementsName: PHReviewIntegrationHandlerRole
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - "sqs:ReceiveMessage"
          - "sqs:DeleteMessage"
          - "sqs:GetQueueAttributes"
        Resource:
          - "*"
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:DescribeTable
          - dynamodb:ListTables
        Resource:
          - ${self:custom.MentionsTableArn}
    environment:
      INTEGRATION_REQUEST_TOPIC_ARN: ${self:custom.IntegrationsTopicArn}
    events:
      - snsSqs:
          name: Event # Required - choose a name prefix for the event queue
          topicArn: ${self:custom.IntegrationsTopicArn} # Required - SNS topic to subscribe to
          batchSize: 1
          visibilityTimeout: 805 # optional (in seconds) - AWS default is 30 secs
          rawMessageDelivery: true # Optional - default value is true
          enabled: true # Optional - default value is true
          filterPolicy: # Optional - filter messages that are handled
            task_type:
              - PRODUCTHUNT_REVIEW


custom:
  pythonRequirements:
    dockerizePip: non-linux
  description: handler for integration requests
  ## Values to be imported from the API stack
  IntegrationsTopicArn:
    Fn::ImportValue: IntegrationsTopicArn
  MentionsTableArn:
    Fn::ImportValue: MentionsTableArn



